### PR TITLE
Fix TorqueSpec working with RSpec 2.13

### LINKED ISSUE #6: Incompatible with rspec 2.13
Torquespec is not compatible with rspec 2.13, rspec 2.5 seems to work.
Im using torquespec 0.6 and torquebox 3.x.incremental.1659.

``` ruby
remote_describe "foo" do
  it "bar" do
    1.should == 2
  end
end
```

```
NoMethodError: undefined method `pending_fixed?' for #<Exception: expected: 2
     got: 1 (using ==)>
   pending_fixed? at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/formatters/base_text_formatter.rb:251
    dump_failures at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/formatters/base_text_formatter.rb:24
             each at org/jruby/RubyArray.java:1617
  each_with_index at org/jruby/RubyEnumerable.java:920
    dump_failures at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/formatters/base_text_formatter.rb:22
         __send__ at org/jruby/RubyBasicObject.java:1703
             send at org/jruby/RubyKernel.java:2209
           notify at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:98
             each at org/jruby/RubyArray.java:1617
           notify at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:97
           finish at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:81
           report at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:36
              run at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:25
              run at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80
          autorun at /usr/local/rvm/gems/jruby-1.7.4/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17
```

### PR DESCRIPTION
**Pull request by slippycheeze**
This should fix #6, implementing the additional features ^W hacks that get newer RSpec versions working correctly with TorqueSpec.  Using these two changes I can successfully run my specs in-container using rspec-core 2.13.0.

### CODE REVIEW

**Comment by swistaczek** [comment]
@daniel-pittman after using Your branch I have issued simillar error:

``` ruby
NoMethodError: undefined method `pending_fixed?' for #<Exception:0x66b9cbe1>
   pending_fixed? at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/formatters/base_text_formatter.rb:165
    dump_failures at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/formatters/base_text_formatter.rb:19
             each at org/jruby/RubyArray.java:1617
  each_with_index at org/jruby/RubyEnumerable.java:920
    dump_failures at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/formatters/base_text_formatter.rb:17
         __send__ at org/jruby/RubyBasicObject.java:1703
             send at org/jruby/RubyKernel.java:2209
           notify at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:98
             each at org/jruby/RubyArray.java:1617
           notify at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:97
           finish at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:81
           report at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:36
              run at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25
   run_in_process at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80
              run at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69
          autorun at /Users/ernest.bursa/.rvm/gems/jruby-1.7.4@beardedhipster/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10
```

**Comment by jcrossley3** [comment]
Thanks!
